In [1]:
import torch
from torch import nn
from torch.nn import functional as F

In [2]:
x = torch.arange(2)
x

tensor([0, 1])

In [3]:
x.shape

torch.Size([2])

In [4]:
x.size()

torch.Size([2])

In [5]:
x.dim()

1

In [6]:
torch.save(x, 'my_tensor')

In [7]:
x2 = torch.load('my_tensor')
x2

tensor([0, 1])

In [8]:
y = torch.zeros(5)

In [9]:
y

tensor([0., 0., 0., 0., 0.])

In [10]:
torch.save([x,y], 'more_tensors')


In [11]:
x2, y2 = torch.load('more_tensors')
x2,y2

(tensor([0, 1]), tensor([0., 0., 0., 0., 0.]))

In [12]:
mydict = {'x': x, 'y': y}
torch.save(mydict, 'mydict')


In [13]:
mydict2 = torch.load('mydict')
mydict2

{'x': tensor([0, 1]), 'y': tensor([0., 0., 0., 0., 0.])}

In [14]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(20, 256)
        self.output = nn.Linear(256, 10)
        
    def forward(self,x):
        return self.output(F.relu(self.hidden(x)))

net = MLP()
X = torch.randn(size=(2,20))
Y = net(X)

In [15]:
torch.save(net.state_dict(), 'mlp.params')

In [16]:
x3 = torch.load('mlp.params')

In [17]:
x3

OrderedDict([('hidden.weight',
              tensor([[ 0.0707, -0.1029, -0.1303,  ...,  0.0349, -0.0993, -0.0808],
                      [ 0.0379,  0.0616, -0.1968,  ..., -0.1461, -0.0362, -0.1181],
                      [-0.1707, -0.1568, -0.0609,  ..., -0.1241,  0.0120,  0.0758],
                      ...,
                      [-0.1496, -0.0878,  0.1481,  ..., -0.0570, -0.0909, -0.1005],
                      [ 0.1766,  0.1130,  0.1621,  ...,  0.0873, -0.0766, -0.1203],
                      [-0.1084,  0.2204, -0.0787,  ..., -0.1758, -0.1619, -0.1801]])),
             ('hidden.bias',
              tensor([-0.0246,  0.1048,  0.0375, -0.2183, -0.1703, -0.2099,  0.0855, -0.1542,
                       0.0039,  0.0778,  0.1646, -0.1054,  0.1446, -0.1712,  0.1332, -0.1331,
                       0.0228,  0.0330, -0.1976,  0.1493, -0.0983,  0.1519,  0.0742,  0.0672,
                       0.1288,  0.0567, -0.1998, -0.0148,  0.0158, -0.2025,  0.1981,  0.1010,
                       0.0598,

In [18]:
clone = MLP()
clone.load_state_dict(torch.load('mlp.params'))
clone.eval()

MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)

In [19]:
Y_clone = clone(X)
Y_clone == Y

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])

In [20]:
def try_gpu(i = 0):
    if torch.cuda.device_count() >= i + 1:
        return torch.device(f'cuda:{i}')
    return torch.device('cpu')

In [21]:
try_gpu()

device(type='cuda', index=0)

In [22]:
net = nn.Sequential(nn.Linear(3,1))
net = net.to(device=try_gpu())

In [27]:
X.shape, X.dim()

(torch.Size([2, 20]), 2)

In [28]:
Z = X.cuda(0)

In [39]:
x = torch.randn(2,3,4)
y = torch.randn(1,3,1)
z =x*y

In [41]:
z.shape

torch.Size([2, 3, 4])

In [42]:
h = torch.randn(2,3)
y = torch.randn(1,1)
h*y

tensor([[ 0.2280, -0.0600, -1.4112],
        [-1.1221,  1.3395, -0.0856]])

In [44]:
net(Z)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x20 and 3x1)

In [57]:
h1 = torch.randn(2,20)
h2 = torch.randn(3,1)
h1_expanded = h1.unsqueeze(0).expand(3,-1,-1)
h2_expanded = h2.unsqueeze(-1).expand(-1, 20, -1)


In [58]:
h1_expanded.shape

torch.Size([3, 2, 20])

In [59]:
h2_expanded.shape

torch.Size([3, 20, 1])

In [60]:
h3 = torch.matmul(h1_expanded, h2_expanded)

In [61]:
b = torch.squeeze(h2_expanded, dim=1)
b.shape

torch.Size([3, 20, 1])

In [63]:
h3.shape

torch.Size([3, 2, 1])

In [64]:
h3_gpu = h3.cuda(0)

In [67]:
new_gpu_tensor = torch.ones(2,3)
new_gpu_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [68]:
new_gpu_tensor = new_gpu_tensor.cuda(0)
net(new_gpu_tensor)

tensor([[-1.5385],
        [-1.5385]], device='cuda:0', grad_fn=<AddmmBackward0>)

In [70]:
class waqar():
    def __init__(self):
        print("im waqar")
    def something_new(self):
        print("this is something new in class waqar")
x = waqar()
x.something_new()

im waqar
this is something new in class waqar


In [72]:
class harry(waqar):
    def __init__(self):
        super().something_new()
harry()

this is something new in class waqar


In [98]:
def array_diff(list_a, list_b):
    for a in reversed(list_a):
        for b in reversed(list_b):
            if a == b:
                list_a.remove(a)
                list_b.remove(b)
    return list_a + list_b

array_diff([1,2],[1])
                
                

    

[2]

In [91]:
list_a = [1,2,4,5,6,7,8]
list_b = [2,3,4,5,6,7]
for i in list_a:
    for b in list_b:
        if i == b:
            list_a.remove(i)
            list_b.remove(i)
          


In [92]:
list_a

[1, 4, 6, 8]

In [93]:
list_b

[3, 4, 6]

In [96]:
list_a = [1,2,4,5,6,7,8]
list_b = [2,3,4,5,6,7]
for i in reversed(list_a):
    for b in reversed(list_b):
        if i == b:
            list_a.remove(i)
            list_b.remove(b)
print(list_a)
print(list_b)

[1, 8]
[3]
