In [1]:
print("how are you?")

how are you?


In [2]:
import torch

In [3]:
print(torch.__version__)

2.0.1+cu117


In [4]:
## introduction to Tensors 
## A way to represent data 
# scalar 
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 

In [6]:
scalar2 = torch.tensor(8)
scalar2

tensor(8)

In [7]:
scalar2.ndim

0

In [8]:
scalar.item()

7

In [9]:
scalar2.item()

8

In [10]:
#vector
vector = torch.tensor([3,4])
vector

tensor([3, 4])

In [11]:
vector.ndim

1

In [12]:
vector.shape

torch.Size([2])

In [13]:
matrix = torch.tensor([[2,3],[2,3]])

In [14]:
matrix

tensor([[2, 3],
        [2, 3]])

In [15]:
tensor = torch.tensor([[[2,3],[5,4],[4,3]]])
tensor

tensor([[[2, 3],
         [5, 4],
         [4, 3]]])

In [16]:
tensor.ndim

3

In [17]:
## random tensors 
random_tensor = torch.rand(3,4)
random_tensor 

tensor([[0.8667, 0.7796, 0.4612, 0.2519],
        [0.2193, 0.6530, 0.4892, 0.9278],
        [0.8070, 0.7847, 0.9314, 0.8071]])

In [18]:
random_tensor_2 = torch.rand(2,3,4,5,6,7)
random_tensor_2

tensor([[[[[[5.4911e-01, 5.7082e-01, 7.4869e-01,  ..., 4.1758e-01,
             1.0211e-01, 8.8446e-01],
            [4.7683e-01, 3.9190e-01, 8.5249e-01,  ..., 7.8900e-01,
             3.3802e-01, 1.1749e-01],
            [7.4109e-01, 6.7218e-01, 5.7557e-01,  ..., 7.7222e-01,
             6.8206e-02, 2.0200e-01],
            [2.0438e-01, 9.6783e-01, 7.0603e-01,  ..., 3.1283e-02,
             6.0932e-01, 7.1834e-01],
            [2.7907e-01, 3.7742e-01, 7.9256e-01,  ..., 8.2821e-01,
             1.9195e-02, 2.1630e-01],
            [5.2102e-03, 8.0481e-01, 4.2336e-01,  ..., 1.7297e-01,
             8.6975e-01, 6.2799e-01]],

           [[8.9832e-01, 8.2506e-01, 2.9415e-01,  ..., 1.3050e-01,
             6.9550e-01, 7.8619e-01],
            [7.1528e-01, 4.8061e-02, 3.0324e-01,  ..., 5.5409e-02,
             7.5410e-01, 2.5866e-01],
            [1.0463e-01, 2.0976e-01, 9.5787e-01,  ..., 1.1727e-01,
             1.7860e-01, 2.3109e-01],
            [3.0435e-01, 3.1715e-01, 7.4191e-01,  ...

In [19]:
random_tensor_2.ndim

6

In [20]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(224,224,3)
random_image_size_tensor

tensor([[[0.5400, 0.2291, 0.4672],
         [0.2556, 0.8828, 0.0871],
         [0.8704, 0.1182, 0.1690],
         ...,
         [0.1319, 0.7869, 0.9740],
         [0.9947, 0.2253, 0.7406],
         [0.0376, 0.9663, 0.6799]],

        [[0.5868, 0.3363, 0.1025],
         [0.1792, 0.5413, 0.0103],
         [0.8153, 0.2017, 0.5507],
         ...,
         [0.0922, 0.3288, 0.7221],
         [0.0234, 0.1294, 0.2890],
         [0.4543, 0.4766, 0.2304]],

        [[0.2810, 0.9660, 0.7423],
         [0.3642, 0.2805, 0.6665],
         [0.8573, 0.7900, 0.7167],
         ...,
         [0.5869, 0.6899, 0.1192],
         [0.9702, 0.6129, 0.0265],
         [0.4040, 0.3447, 0.0636]],

        ...,

        [[0.5617, 0.3129, 0.5384],
         [0.5364, 0.1348, 0.7226],
         [0.1918, 0.7384, 0.3432],
         ...,
         [0.8453, 0.3797, 0.0581],
         [0.3123, 0.7147, 0.8479],
         [0.0370, 0.9589, 0.7515]],

        [[0.5810, 0.4879, 0.1125],
         [0.6068, 0.0322, 0.0745],
         [0.

In [21]:
## zero and ones tensors 
zeros = torch.zeros(size=(3,5))
zeros

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [22]:
ones = torch.ones(size=(2,2))
ones

tensor([[1., 1.],
        [1., 1.]])

In [23]:
ones.dtype

torch.float32

In [24]:
### creating a range of tensors and tensor-like 
# use torch.range()
torch.range(0,10)

/tmp/ipykernel_4763/3254165869.py:3: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [25]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
one_to_thousand = torch.arange(start = 2, end = 1000, step = 20)
one_to_thousand

tensor([  2,  22,  42,  62,  82, 102, 122, 142, 162, 182, 202, 222, 242, 262,
        282, 302, 322, 342, 362, 382, 402, 422, 442, 462, 482, 502, 522, 542,
        562, 582, 602, 622, 642, 662, 682, 702, 722, 742, 762, 782, 802, 822,
        842, 862, 882, 902, 922, 942, 962, 982])

In [27]:
float_tensor = torch.tensor([2,3,5], dtype = None, device = None, 
                           requires_grad = False)
float_tensor

tensor([2, 3, 5])

In [28]:
float_tensor.dtype

torch.int64

In [29]:
float_32_tensor = torch.tensor([3.0, 2.0, 3.0])
float_32_tensor

tensor([3., 2., 3.])

In [30]:
float_32_tensor.dtype

torch.float32

In [31]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 2., 3.], dtype=torch.float16)

In [32]:
float_16_tensor * float_32_tensor

tensor([9., 4., 9.])

In [33]:
int_32_tensor = float_32_tensor.type(torch.int32)
int_32_tensor

tensor([3, 2, 3], dtype=torch.int32)

In [34]:
float_16_tensor * int_32_tensor

tensor([9., 4., 9.], dtype=torch.float16)

In [35]:
float_16_tensor.device

device(type='cpu')

In [36]:
if torch.cuda.is_available():
    tensor_on_gpu = float_16_tensor.to(device="cuda")
    print("New device:", tensor_on_gpu.device)
else:
    print("CUDA not available. Cannot move to GPU.")

New device: cuda:0


## manipulating tensors (tensor operations)


### tensor operation 

In [37]:
# addition of tensors 
tensor3 = torch.tensor([1,2,3])
tensor3 + 10

tensor([11, 12, 13])

In [38]:
# torch.add(tensor3, 10)

In [39]:
tensor1 = torch.tensor([1,2])
tensor4 = torch.tensor([2,3])
import time

In [40]:
%%time
tensor5 = torch.matmul(tensor1, tensor4)

CPU times: user 783 µs, sys: 229 µs, total: 1.01 ms
Wall time: 12.5 ms


## matrix transpose 

In [41]:
tensor1.T

/tmp/ipykernel_4763/368355069.py:1: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3571.)
  tensor1.T


tensor([1, 2])

In [43]:
tensor1.shape

torch.Size([2])

In [46]:
tensor6 = torch.rand([2,4])

In [47]:
tensor6

tensor([[0.2540, 0.7556, 0.9879, 0.7341],
        [0.8757, 0.6411, 0.4368, 0.6668]])

In [48]:
tensor6.T

tensor([[0.2540, 0.8757],
        [0.7556, 0.6411],
        [0.9879, 0.4368],
        [0.7341, 0.6668]])

# finding min, max, mean and sum 

In [49]:
x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [50]:
#find min
torch.min(x)

tensor(0)

In [51]:
#find max
torch.max(x)

tensor(90)

In [53]:
#find mean
torch.mean(x.type(torch.float32))

tensor(45.)

In [54]:
#find sum
torch.sum(x)

tensor(450)

# finding positional(index) min and max 

In [55]:
torch.argmin(x)

tensor(0)

In [56]:
torch.argmax(x)

tensor(9)

In [57]:
print("working")

working


# Reshaping, stacking, squeezing and unsqueezing tensors


In [58]:
a = torch.arange(1, 10)
a

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
a.shape

torch.Size([9])

In [67]:
#reshape
#add an extra dimention
a_reshaped = a.reshape(9,1)

In [68]:
a_reshaped

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [69]:
a

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
a.T

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
y= a.T

In [72]:
y


tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
#stack tensors on top of each other
a_stacked = torch.stack([a,a,a,a])

In [80]:
a_stacked

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [81]:
# torch.squeeze()
a_reshaped

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [82]:
a.shape

torch.Size([9])

In [83]:
a_reshaped.shape

torch.Size([9, 1])

In [85]:
a_squeezed = a_reshaped.squeeze()

In [87]:
a_squeezed.shape

torch.Size([9])

In [95]:
a_unsqueeze = a_squeezed.unsqueeze(dim=1)

In [96]:
a_unsqueeze.shape

torch.Size([9, 1])

In [97]:
a_unsqueezed = a_squeezed.unsqueeze(dim=0)

In [98]:
a_unsqueezed.shape

torch.Size([1, 9])

In [99]:
#permutation 
x_orignal = torch.rand(size = (224,224,3))
x_orignal

tensor([[[0.5309, 0.4832, 0.2938],
         [0.7531, 0.0082, 0.3489],
         [0.4733, 0.0932, 0.2044],
         ...,
         [0.3470, 0.9315, 0.5093],
         [0.1117, 0.1794, 0.8548],
         [0.3033, 0.7391, 0.5233]],

        [[0.5134, 0.6463, 0.3041],
         [0.8672, 0.0665, 0.1145],
         [0.5537, 0.7016, 0.0810],
         ...,
         [0.9517, 0.1846, 0.1116],
         [0.3130, 0.9258, 0.5377],
         [0.4758, 0.7839, 0.5002]],

        [[0.1432, 0.7848, 0.0513],
         [0.3440, 0.9523, 0.2548],
         [0.3375, 0.8499, 0.9645],
         ...,
         [0.8814, 0.1085, 0.7059],
         [0.5947, 0.8523, 0.8449],
         [0.7480, 0.5436, 0.7699]],

        ...,

        [[0.0865, 0.6245, 0.6197],
         [0.5309, 0.9869, 0.6026],
         [0.3651, 0.6386, 0.3345],
         ...,
         [0.9279, 0.1646, 0.1967],
         [0.4207, 0.2723, 0.2039],
         [0.2065, 0.2310, 0.0045]],

        [[0.6705, 0.4969, 0.3013],
         [0.6190, 0.0346, 0.0617],
         [0.

In [100]:
x_permute = x_orignal.permute(2,0,1)

In [102]:
x_permute.shape

torch.Size([3, 224, 224])

In [106]:
#reproducibility of random numbers with random seeds(manual_seed)
RANDOM_SEED = 42 
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C == random_tensor_D)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
